# API-Schlüssel für CoinMarketCap
CMC_API_KEY = "9e400d00-7bff-42e8-898d-0ddf6a6d8fc7"

# E-Mail-Konfiguration für GMX
EMAIL_HOST = "mail.gmx.net"
EMAIL_PORT = 587
EMAIL_USER = "deineadresse@gmx.de"
EMAIL_PASS = "dein_app_passwort"

